stages: 
  - build 
  - test 
  - deploy 

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

Build: 
  image: gradle:4.6-jdk8-alpine 
  stage: build 
  script: 
    - ./gradlew build
  only:
    - master
    - develop
    - feature/EditCourseSurvey
    - feature/error-handeling
    - feature/cleancode
  tags:
    - ugrad

Test: 
  image: gradle:4.6-jdk8-alpine 
  stage: test 
  only:
    - master
    - develop
    - feature/EditCourseSurvey
    - feature/error-handeling
    - feature/cleancode
  script:
    - ./gradlew check
  tags:
    - ugrad
    
Production: 
  stage: deploy 
  image: ruby:2.3
  script: 
    - ruby -v
    - gem install dpl 
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  tags:
    - dalfcs_gitlab_docker_ci
  only:
    - master
    - develop